#Problem 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  #By starting with 1 and 2, the first 10 terms will be:
      #1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  #Find the sum of all the even-valued terms in the
  #sequence which do not exceed four million.

termone = 1
termtwo = 2
total = 2

while termone < 4000000:
    termthree = termone + termtwo
    termone = termtwo
    termtwo = termthree
    if termtwo % 2 == 0:
        total = total + termtwo
        print total
        
#to test: termone, termtwo, termthree. termone+termtwo = termthree. termone = termtwo. termtwo = termthree. repeat.
