def helpmenu():
    print "                                                                 "
    print "              --------------------------------------             "
    print "              The Help Commands for Text Game 3 are:             "
    print "              --------------------------------------             "
    print "                                                                 "
    print "Menu Commands:                                                   "
    print "  * new  - Starts a new game with a new character.               "
    print "  * help - Takes you to the Help screen to view a list of        "
    print "           commands                                              "
    print "  * quit - Quits the game                                        "
    print "                                                                 "
    print "Game Commands:                                                   "
    print "  * ? -                                                          "
